SFDO-Tooling/Snowfakery

- requirements_dev.txt
- snowfakery/cli.py
- snowfakery/data_generator.py
- snowfakery/output_streams.py
- snowfakery/utils/template_utils.py
- tests/test__main__.py
- tests/test_cli.py
- tests/test_output_streams.py
- tests/test_with_cci.py
- tests/utils.py
Increasing test coverage and Windows support and fixing bugs found in that process.
In the file cli.py, I removed the broken --start-ids feature and use a context manager for outputstreams to close them. Let Output Streams open and close their old file handles.
In datagenerator.py I allow click's LazyFile which is not a proper subclass of Python TextIO
In OutputStreams I have a base class that manages open and closing file handles. Also cleaned up connection handling somewhat in SQLOutputStream and create everything (base, metadata, etc.) in the initializer rather than in the middle of the code.
In test files, increase coverage and remove uses of NamedTemporaryFile which is basically unusable on Windows. I created a new utility (in test/utils.py) for that.
> Placeholder: Feature/coverage

- tests/test_with_cci.py
Forgot one Windows incompatibility because it is gated by CCI availability. (in other words it is only triggered on the part of the matrix which is CCi-available/running on Windows)
> Last change needed to be Windows compatible

- setup.py
This is intended to make it so that we don't have to make a new snowfakery release every time CumulusCI updates its required version of one of the dependencies it shares with snowfakery.
> Pin minimum requirements in setup.py

- snowfakery/template_funcs.py
Date parsing takes a lot of time and we only ever parsing dates from the actual recipe, never from Faker. Since the recipe is relatively small, we might as well just cache the result of parsing the dates.
> Cache parsed dates

- snowfakery/data_generator.py
- snowfakery/data_generator_runtime_dom.py
- snowfakery/generate_mapping_from_factory.py
- snowfakery/parse_factory_yaml.py
- tests/cci/record_types.yml
- tests/test_generate_mapping.py
Renamed some internal attributes for clarity in data_generator.py and parse_factory_yaml.py
Delete some confusing commentary in data_generator_dom.py.
Add record_type support to generate_mapping_from_factory.py
Capture the table name on TableInfo objects so that when we clone them for record type objects, we still know what table they came from.
Add tests and a test recipe.
> Add support for Salesforce record types to Snowfakery

- CONTRIBUTING.rst
- HISTORY.md
- snowfakery/version.py
> Snowfakery 0.8.1

- snowfakery/__init__.py
- snowfakery/data_generator_runtime.py
- snowfakery/plugins.py
- snowfakery/template_funcs.py
- tests/test_custom_plugins_and_providers.py
- tests/test_template_funcs.py
Instead of having a different way of pulling standard library functions into the interpreter, they are now a plugin like any other one. The only difference is the unavoidable one, which is that they are promoted to the top namespace rather than being nested in a plugin namespace.
In order to allow this, I exposed the @lazy decorator to plugin authors and documented it in the Quip doc.
There was some quite inefficient code related to the old way of doing the standard library (injecting runtime context over and over, instead of looking it up lazily), so this should result in a modest performance improvement.
> Use plugin architecture for builtin functions

- snowfakery/output_streams.py
- tests/mapping_vanilla_sf.yml
This code should eventually be replaced by code in CumulusCI, but as long as it is here, it should be correct.
When I wrote it, I didn't know or forgot that two different mapping steps can generate the same table.
It isn't smart about merging columns from multiple steps, but neither is CCI.
> Fix duplicate table issues similar to CCI

- snowfakery/parse_recipe_yaml.py
- tests/test_parse_recipe_yaml_internals.py
Occasionally paths are byte-arrays and this decodes them however is "appropriate" for the platform. I ran into this when I was using Snowfakery with FIlesystem2.py
> Decode paths to Python strings

- docs/index.md
- snowfakery/data_generator_runtime.py
- snowfakery/data_generator_runtime_object_model.py
- tests/test_template_funcs.py
Add a feature that allows you to know what your count is within your parent element.
This feature is already documented on master. (the documentation preceded the feature!)
> Add child_count feature

- snowfakery/cli.py
- snowfakery/data_gen_exceptions.py
- snowfakery/parse_recipe_yaml.py
- tests/test_errors.py
- tests/test_parse_recipe_yaml_internals.py
Previously if the user had errors in their YAML file, they would see a Python traceback. Now they will see just a short summary of the error without the traceback.
> Suppress traceback for YAML errors

- docs/index.md
- snowfakery/data_gen_exceptions.py
- snowfakery/data_generator.py
- snowfakery/data_generator_runtime.py
- snowfakery/data_generator_runtime_object_model.py
- snowfakery/output_streams.py
- snowfakery/template_funcs.py
- tests/broken_forward_reference.yml
- tests/forward_reference.yml
- tests/test_data_generator.py
- tests/test_generate_mapping.py
- tests/test_references.py
Support Snowfakery files like this:
```
- object: A
fields:
B:
reference: Bob. # referenced before it is defined.
- object: B
nickname: Bob
fields:
A:
reference: A
```
A new object is created called EmptySlot which is allocated each time the recipe is instantiated, analogous to local variable slots in Python, or NamedTuple slots.
When a slot is allocated, it grabs a database ID just as an ObjectRow would. Then, when the object is created, it uses that ID.
If the ID is never used by any ObjectRow, that will cause a reportable error.
> Allow forward references to nicknames.

- snowfakery/parse_recipe_yaml.py
- tests/macros-include-macros.yml
- tests/macros-recurse-unbounded.yml
- tests/test_macros.py
For example:
```
- macro: foo
fields:
foobar: FOOBAR
- macro: bar
include: foo
fields:
barbar: BARBAR
- object: Bar
include: bar
```
Generates:
```
Bar(id=1, barbar=BARBAR, foobar=FOOBAR)
```
> Macros can include other macros

- CONTRIBUTING.rst
- HISTORY.md
Should have done this before the release but the release object on Github has the same text as below regardless.
> Snowfakery 1.1 features plus Markdown lint cleanups.

- docs/index.md
- snowfakery/data_generator_runtime.py
- snowfakery/data_generator_runtime_object_model.py
- snowfakery/output_streams.py
- snowfakery/plugins.py
- snowfakery/template_funcs.py
- tests/test_custom_plugins_and_providers.py
Outputstreams will call "simplify" for PluginResults.
Example is in test_custom_plugins_and_providers
Lazy plugins can either ask for their parameters to be simplified
by calling context.evaluate() or they can use
context.evaluate_raw() if they don't care at all about the data
of their parameters (higher order function-type stuff).
A few type definitions moved around to permit code reuse without
circular references.
> PluginsResults with complex state state can implement "simplify"

- docs/index.md
- snowfakery/cli.py
- tests/test_cli.py
The target-number command line was not documented. Now it is.
While documenting it, I thought it would be better if it read in the same order as English: "50 Account"(s). Both orders are supported in the code, however.
> Document and improve usability of target-number feature

- docs/index.md
- snowfakery/template_funcs.py
- tests/test_template_funcs.py
The docs described a more concise form of random_choice that was not actually implemented. Now it is. The more verbose form is still available and its motivation is described in the documentation.
> Implement a shorter form of random_choice

- snowfakery/template_funcs.py
- tests/test_template_funcs.py
A couple of corner cases which changed in recent versions.
Allow "none" as a return code from random_choice because sometimes NULL is a real choice.
Allow random_choice with a single item. It previously allowed this. Machine-generated Snowfakery files may sometimes generate a single-item random_choice.
> Handle some corner cases

- snowfakery/data_generator_runtime.py
- tests/test_restartability.py
Do not serialize deep object references to continuation file. They sometimes cause reference loops which YAML cannot (in this case) load.
> Do not serialize deep object references to continuation file

- snowfakery/data_generator_runtime.py
- snowfakery/template_funcs.py
- tests/test_data_generator.py
- tests/test_data_generator_runtime.py
- tests/test_restartability.py
The Snowfakery docs say:
> references are always to objects
created within the current "batch" of a recipe and never to a previous
batch with only one exception: objects marked 'just_once' are always
created only in the first run and references to them are to the
objects created in that first batch.
Given this, there is no point keeping track of objects created in previous iterations of the recipe other than those with nicknames, so Snowfakery does not do that anymore.
Also fixes two bugs which could cause crashes relating to the intersection of a) forward references, b) nicknames and c) continuations.
One solution is not to serialize "nickname slots" into the continuation file because they add no value and we are not trying to serialize deep hierarchies of ObjectRows.
A second bugfix is …
> Fixes relating to continuation handling.

- snowfakery/template_funcs.py
- tests/test_template_funcs.py
Improve casting of datetimes to dates and test coverage
Previously, datetimes would be returned unchanged. Now, the time part will be truncated properly.
> Improve casting of datetimes to dates and test coverage

- snowfakery/cli.py
I just ran into this while copy and pasting from the help text. Results in: `Error: no such option: --output_format`
* Fixed option names in the help text.
> Fix option names in help text

- docs/index.md
Documentation fix:
Clarify that case is significant in date formats
> Clarify that case is significant in date formats

- examples/EDA/eda_macros.yml
- examples/EDA/eda_objects.yml
- examples/npsp/Contact_npsp.recipe.yml
- examples/salesforce/Contact.recipe.yml
- snowfakery/data_generator_runtime.py
- tests/test_data_generator_runtime_dom.py
- tests/test_template_funcs.py
Changes: 
1. all examples use the new syntax (except a couple of unit tests)
2. if a template uses both syntaxes, the new syntax parts will work properly. The old syntax parts won't. This is better than the previous situation which would guide you to the conclusion that the problem is in the new-style syntax.
> Use new syntax everywhere

- snowfakery/output_streams.py
As long as we are using a Blue colour in the bubbles generated by Snowfakery, the colour might as well match the logo on my slides.
> Official salesforce blue

- snowfakery/cli.py
- snowfakery/data_generator_runtime_object_model.py
- snowfakery/output_streams.py
- snowfakery/parse_recipe_yaml.py
- snowfakery/standard_plugins/Salesforce.py
- tests/test_cli.py
- tests/test_output_streams.py
- tests/test_with_cci.py
Things I noticed after reviewing the code with Brandon and Aishanya.
In the early days of Snowfakery, mapping files were inputs rather than outputs. The last vestiges of those days are removed in this pull request.
In the early days of Snowfakery, references were inferred at parse time rather than on the basis of an actual execution of the recipe. Therefore a special "Reference" object was added to the parse tree for this analysis. Now the analysis is based on the output and the special Reference object is not needed.
A few other doc cleanups.
> Code cleanups

- snowfakery/output_streams.py
Rows with no names would output "id" twice. Now they do not.
> Image Output Cleanup

- cumulusci.yml
- docs/index.md
- examples/binary.recipe.yml
- examples/salesforce/ContentVersion.recipe.yml
- examples/salesforce/example.pdf
- examples/text.recipe.yml
- snowfakery/standard_plugins/Salesforce.py
- snowfakery/standard_plugins/base64.py
- snowfakery/standard_plugins/file.py
- tests/test_custom_plugins_and_providers.py
- tests/test_salesforce_gen.py
Allow binary or text data to be included and sent to Salesforce. Described in docs.
> Allow binary or text data to be included and sent to Salesforce

- requirements/dev.in
- setup.py
- tox.ini
* Fixed requirements file to use for dependencies in `tox.ini`
* Fixed parsing of new format of requirements files in setup.py
* Pinned Sphinx to `<4` instead of an exact version.
> `pip-tools`: additional fixings

- .github/workflows/ci.yml
- examples/math.yml
- snowfakery/standard_plugins/_math.py
- tox.ini
Works around Python issue and adds Python 3.9 to Ubuntu and Windows test matrices.
> Python 3.9 support, especially for math

- snowfakery/fakedata/fake_data_generator.py
- tests/test_faker.py
- tests/test_locales.py
Allow names to use a Salesforce naming convention: 
phone_number -> PhoneNumber
Alternate spellings are all valid:
phonenumber
PhoneNumber
phone_number (original)
PHONENUMBER
In the unlikely case of there being names ab_cd and abc_d, the caller can use underscores to disambiguate.
> Allow names to use a Salesforce naming convention

- docs/index.md
- snowfakery/api.py
- snowfakery/cli.py
- tests/test_cli.py
Add rep-counting as an API option with the `__REPS__` field replacing the tablename in stopping criteria.
Add --reps as a CLI option.
> Allow user to repeat recipe by specifying reps

- docs/extending.md
- snowfakery/plugins.py
- snowfakery/standard_plugins/file.py
Some plugins need to deal with relative paths and therefore they need to know the filename of the parent, to know what their values are relative to.
Existing test cover this code and upcoming PRs will exercise it as well.
> Plugins have access to file paths

- cumulusci.yml
VCR has recorded API calls with version 50.0. Salesforce is now delivering 52.0 orgs.
The place where I would add some magic to make it work without pinning is in CCI, not Snowfakery, so this is a workaround until I can fix it better in CCI.
> Pin a version to make VCR happy.

- snowfakery/data_generator_runtime.py
- snowfakery/standard_plugins/Salesforce.py
- snowfakery/standard_plugins/datasets.py
Some extra code to ensure that datasets are closed in an orderly fashion. Should fix a Tempfile-related exception on Windows.
> Close datasets properly

- snowfakery/cci_mapping_files/declaration_parser.py
- tests/cci/mapping_mixins.load.yml
- tests/cci/test_declaration_parser.py
Snowfakery-in-CCI now allows users to set the batch_size and anchor_date for dataloads.
> Support all relevant mapping features in load.yml

- snowfakery/data_generator_runtime.py
- snowfakery/data_generator_runtime_object_model.py
- snowfakery/standard_plugins/Salesforce.py
- snowfakery/template_funcs.py
- tests/parent-child-just-once.yml
- tests/test_continuation.py
- tests/test_references.py
Previously, the `random_reference` feature could not refer to objects created with just_once.  This has been corrected.
> Parent child just once bugfix

- snowfakery/parse_recipe_yaml.py
- tests/bad_random_choice_keys.yml
- tests/random_choice.yml
- tests/test_custom_plugins_and_providers.py
- tests/test_template_funcs.py
random_choice has a short-form key:probability syntax. Now that short-form syntax can be used for booleans and dates, not just strings.
> Allow bools and dates as options for random_choice's short syntax

- docs/index.md
- snowfakery/standard_plugins/UniqueId.py
Previously, each unique ID generator was initialized with an 8 bit random number. Now it is initialized with 
a counter value instead. Each generator will thus start at a different point, but not a random point.﻿
This fixes some intermittent test failures and otherwise weird behaviour.
> unique_id without rand

- snowfakery/fakedata/fake_data_generator.py
- tests/test_faker.py
Usernames are now limited to 80 chars to match Salesforce rules.
Fixes #546 . Thanks for reporting, @mirvinecx1
> Limit usernames to 80 chars

- snowfakery/utils/template_utils.py
- tests/test_template_utils.py
- tests/test_types.py
Snowfakery infers integers from digit strings in Jinja templates. The old pattern would strip leading zeros from digit strings starting with 0. (01234 => 1234). This is especially problematic for US postal codes as discovered in #479.
This patch leaves 0-prefixed strings as strings.
> Allow zero-prefixed strings of digits

- mkdocs.yml
- requirements/dev.in
- requirements/dev.txt
- tools/faker_docs_utils/docs_config.yml
- tools/faker_docs_utils/summarize_fakers.py
There are two things in this branch:
1. Config for mkdocs search index build to prevent extremely slow searching:
https://snowfakery.readthedocs.io/en/latest/search.html?q=postcode
versus:
https://snowfakery.readthedocs.io/en/feature-dont-search-locales/search.html?q=postcode
2. While I was researching I noticed that the index is bloated by Fake data for things like "fake tarfile", "take zipfile" etc. Now I have a feature for ignoring those.
> Do not search locales and do not document "fake: zipfile" and similar irrelevant fakers

- tests/test_embedding.py
Capture a warning in a test case instead of printing it to the console.
> Clean up a warning

- snowfakery/standard_plugins/datasets.py
- tests/badcsv_too_many_columns.csv
- tests/test_external_datasets.py
Better error checking for the case where a CSV Row has too many columns.
> Check for case where CSV Row has too many columns

- snowfakery/data_generator_runtime.py
I had used ScalarTypes in one of the two places where I had used Scalar.__args__. Now it's in both places.
> Use ScalarTypes everywhere

- snowfakery/template_funcs.py
- tests/test_datetimes.yml
- tests/test_output_streams.py
datetime() function will now behave like the fake data providers w.r.t timezones
Extension of:
https://github.com/SFDO-Tooling/Snowfakery/pull/601
I forgot this part.
> datetime() function should behave like faker w.r.t timezones

- docs/index.md
- snowfakery/template_funcs.py
- tests/test_template_funcs.py
Adds a function for inspecting the value of a Snowfakery value in a recipe.
Might be helpful for debugging recipe issues that arise from the NativeTypes feature.
> Add a debug function to Snowfakery.

- snowfakery/template_funcs.py
- tests/test_references.py
A synthetic reference is when you know the 'id' of the thing
you want to reference and you want Snowfakery to treat it as
a reference. It is analogous to casting a pointer in C.
Currently this is not documented, because the internal id
mechanism isn't documented and may change. But it is useful
for some upcoming Salesforce-internal features and projects.
Once it's been tested there we can figure out how to make
it more widely available.
Probably in the long run, we will allow users to control their own 
'id' mechanism on a per sObject basis. Then synthetic 
references-by-id will make sense to them and we can document
it.
> Allow synthetic references

- examples/native_types_differences.yml
- schema/snowfakery_recipe.jsonschema.json
- snowfakery/data_generator.py
- snowfakery/data_generator_runtime.py
- snowfakery/parse_recipe_yaml.py
- snowfakery/standard_plugins/SnowfakeryVersion.py
- tests/errors/bad_version.recipe.yml
- tests/test_dates.py
- tests/test_faker.py
- tests/test_version.py
The way Jinja-in-Snowfakery was configured before, all objects were serialized to strings before being captured as fields. This change defers the serialization to the output_stream which allows operations like:
foo: ${{OtherObj.IntField + 5}}
or
foo: ${{OtherObj.DateField + relativedelta(days=3)}}
etc.
Allowing formulas to manipulate values that do not start or end as strings will have a variety of benefits.
It is theoretically possible that this will break a recipe, but it will break a very tiny number. As an example, this would have previously generated a string, and will now generate an error:
foo: ${{"".class}}
> Native types instead of strings

- docs/index.md
- snowfakery/data_generator_runtime.py
- tests/test_datetime.yml
- tests/test_now.yml
- tests/test_template_funcs.py
The `now` variable returns a datetime representing the current moment. It stores microsecond precision.
> Add 'now' variable to Snowfakery

- docs/index.md
- tests/test_template_funcs.py
I had a test that was checking whether subsequent calls to now() were guaranteed to generate different values for use as uniquifying timestamps. The answer seems to be "no" on Windows, so I've removed the test and documented the situation.
> Document that now() does not generate unique results

- snowfakery/data_generator_runtime.py
- snowfakery/data_generator_runtime_object_model.py
- snowfakery/output_streams.py
- snowfakery/utils/template_utils.py
- tests/decimal.yml
- tests/test_faker.py
- tests/test_types.py
Decimal fakers were causing a problem because there was no serialization rule for them.﻿
In the process of fixing it I discovered another small bug relating to this syntax:
fieldname: ${{fake.foo}}
This was causing an exception in the new Native Types mode of Snowfakery. Now it's fixed.
> Allow decimal datatype

- tests/conftest.py
Snowfakery's integration testing infrastructure is based on CumulusCI's. CumulusCI's now depends on client apps declaring the `salesforce_serializer`. This PR declares a `salesforce_serializer` which is just the default VCR serializer. Snowfakery doesn't need the compressed serializer yet.
> Make Snowfakery compatible with latest CCI

- snowfakery/row_history.py
- tests/test_references.py
This case failed previously:
```
- object: A
just_once: True
- object: A
- object: A
nickname: nicky
fields:
name: nicky
- object: B
count: 2
fields:
A_ref:
random_reference: nicky
nameref: ${{A_ref.name}}
```
It would not find "nicky" properly. It would find one of the other "A" objects.
> Keep track of nicknames for counters

- snowfakery/utils/pickle.py
- tests/test_references.py
During Code Review we noticed that recipes that make DEEP references (a.b.c.d)
to objects which are connected by nesting rather than by reference, would not
work because the nested objects are not serialized.
The reason that they were not being deep pickled was because the pickler for Saving rows was detecting some code which had been written for serializing to YAML for continuations in __getstate__. This code bypasses the __getstate__ code.
> Deep Pickles

- docs/salesforce.md
- snowfakery/standard_plugins/Salesforce.py
- tests/test_with_cci.py
`find_record` is now cached so that it only calls into Salesforce once. A future PR could add an opt-out for this feature, but for now I can't think of use-cases for the opt-out.
> Cache records for performance

- .github/workflows/ci.yml
There's a failure here:
When both base and branch are "main" it attempts to check it out with the same name twice. This new logic will check it out under two names and then conclude that there is no diff and thus no uncovered lines. When it really is a branch, it should behave as before.
> Instead of env var BASE_REF, name the local _remote_main_

- docs/index.md
- snowfakery/output_streams.py
- snowfakery/template_funcs.py
- tests/test_dates.py
- tests/test_datetime.yml
- tests/test_fake_datetimes.yml
- tests/test_faker.py
Add `datetime_between` feature
Allow datetimes to be parsed from strings
Allow datetimes to be coerced from dates
> Datetime features

- tools/faker_docs_utils/mkdocs_plugins/main_mkdocs_plugin.py
This cache was turned off because of a Faker change and the consequences were bad.
With caching, building the Faker docs took about 8[ minutes](https://github.com/SFDO-Tooling/Snowfakery/actions/runs/1650674753/jobs/2229420189).
With no caching, they took 30 [minutes](https://github.com/SFDO-Tooling/Snowfakery/actions/runs/3140455319).
Now they are back to 8 [minutes](https://github.com/SFDO-Tooling/Snowfakery/actions/runs/3155971564/jobs/5135195733)
> Speed up docs build with caching

- .github/workflows/ci.yml
We removed test subdirectories from our binary distribution of CumulusCI in SFDO-Tooling/CumulusCI/#3476. This broke the `with_cumulusci` job in our CI workflow because of our dependency on a pytest plugin upstream. This PR forces the use of CumulusCI's source distribution (actually the main branch entirely), which does include the subdirectories we need.
We'll switch to using the source distribution after the next release.
> Use CumulusCI source distribution in CI

- .pre-commit-config.yaml
- snowfakery/data_generator.py
- tests/standard_functions/test_distributions.py
- tests/test_cli.py
- tests/test_continuation.py
- tests/test_custom_plugins_and_providers.py
- tests/test_data_generator.py
- tests/test_faker.py
- tests/test_i18n.py
- tests/test_inclusions.py
- tests/test_macros.py
- tests/test_parse_samples.py
- tests/test_references.py
- tests/test_structured_values.py
- tests/test_template_funcs.py
- tests/test_types.py
Snowfakery has updated its output-mocking strategy over the years.
An upcoming change needs pervasive changes to all output-mocks.
So this PR also centralized all of them through a single fixture called 
generated_rows. Lots of old code like this:
@mock.patch(write_row_path)
def test_gen_standard_objects(self, write_row):
with open(standard_objects) as open_yaml_file:
generate(open_yaml_file, {}, None)
calls = write_row.mock_calls
Is updated to modern syntax:
def test_gen_standard_objects(self, generated_rows):
with open(standard_objects) as open_yaml_file:
generate(open_yaml_file, {}, None)
calls = generated_rows.mock_calls
> Unify mocking strategy across all tests.

- snowfakery/data_generator_runtime.py
- snowfakery/standard_plugins/Schedule.py
- snowfakery/standard_plugins/datasets.py
In snowfakery/data_generator_runtime.py : print more information about the exception by using repr(e) instead of str(e)
In several other files, put a message in every NotImplementeError
And make sure that FileDatasets have a close() method so it doesn't generate warnings.
> Clean up warnings in tests and at runtime.

- snowfakery/standard_plugins/Salesforce.py
- snowfakery/standard_plugins/datasets.py
- tests/multiple-datasets.yml
Fixes #901
What was happening on Windows is that that the temporary directory was being garbage collected before the open file handle temporary file inside of it. This was probably also handling on *ix, but it was harmless.
On Windows, the temporary directory object needs to live a bit longer than the local tempfile, which needs to live a bit longer than than the SQL Alchemy connection to the tempfile.
So I use an ExitStack to inject cleanup code which is run before the connection is closed and the file handle is released.
All of this is triggered by the garbage collector letting go of the iterator when the recipe is finishing up.
It might be better to do a deterministic, explicit, top-down cleanup, but that should probably be a different PR.
> Clean up temporary directories after closing iterator
