snowfakery/data_generator_runtime_dom.py, snowfakery/standard_plugins/statistical_distributions.py, tests/standard_functions/test_distributions.py
Distributions that meet various statistical patterns. Plugin will not load if NumPy is not available, but that's probably okay for this use-case.
Also a small improvement to plugin error handling.
=> Statistical distributions in the new Plugin format.

setup.py, snowfakery/cli.py
Should be to invoke it as just 'snowfakery' on a command line.
=> Add a CLI entry point for Snowfakery

snowfakery/docs/examples/st_ives.yml
=> Add St. Ives example.

.github/workflows/ci.yml, setup.py, snowfakery/data_generator_runtime_dom.py, snowfakery/standard_plugins/statistical_distributions.py, tests/standard_functions/test_distributions.py, tests/test_cli.py, tests/test_data_generator.py, tests/test_parse_samples.py, tests/test_restartability.py
Just code reformatting so I can turn on the pre-commit hooks.
=> Turn on black and pre-commit hooks

snowfakery/parse_factory_yaml.py, snowfakery/plugins.py
A few files that slipped through my Black sweep because they were on branches.
=> Last black cleanups.

.dependabot/config.yml, CONTRIBUTING.rst, Makefile
Add dependabot config, CONTRIBUTING.rst and Makefile.
=> Tools for 3rd party contributors.

HISTORY.md, snowfakery/version.py
Windows compatibility improved, especially in test cases.
Changed the syntax for CSV handling.
Added --output-folder command.
=> Snowfakery version 7.

requirements.txt, requirements_dev.txt
Update Fakery, Jinja2, Coverage and Pre-commit.
=> Dependency updates

examples/simple-salesforce.yml, tests/test_parse_samples.py
Add a good example for on-ramping which uses S.F.'s advanced features only lightly or not at all.
=> Add simplistic salesforce example.

requirements_dev.txt, snowfakery/data_generator.py, snowfakery/generate_mapping_from_factory.py, snowfakery/template_funcs.py, tests/test_cli.py, tests/test_i18n.py, tests/test_line_numbers.py, tests/test_output_streams.py
(I ran tox to make sure the update to pytest-cov didn't break anything, and that appears to have run black on some files where it wasn't run before.)
=> update dependencies and run black

.coveragerc, snowfakery/data_generator_runtime_dom.py, tests/test_custom_plugins_and_providers.py, tests/test_data_generator_runtime_dom.py, tests/test_errors.py
More consistent error reporting using a helper.
=> Improve error reporting

.coveragerc, examples/simple-salesforce.yml, snowfakery/data_generator_runtime.py, snowfakery/data_generator_runtime_dom.py, snowfakery/docs/examples/formula_1.yml, snowfakery/docs/examples/st_ives.yml, snowfakery/template_funcs.py, tests/BDI_generator.yml, tests/CharacterGenTest.yml, tests/gen_npsp_standard_objects.yml, tests/gen_sf_standard_objects.yml, tests/gender_conditional.yml, tests/npsp_standard_objects_macros.yml, tests/sf_standard_object_macros.yml, tests/test_custom_plugins_and_providers.py, tests/test_data_generator_runtime_dom.py, tests/test_errors.py, tests/test_faker.py, tests/test_line_numbers.py, tests/test_output_streams.py, tests/test_structured_values.py, tests/test_template_funcs.py
Switch from <<X>> syntax to ${{X}} syntax.
=> Syntax overhaul

docs/index.md
=> Add documentation about the math plugin

HISTORY.md, README.md, setup.py, snowfakery/version.py
PyPI gets its UI metadata from the package rather than from an admin interface.
=> Update URLs for PyPI. No changes to the Snowfakery code itself

snowfakery/output_streams.py, tests/test_cli.py
Previously if Snowfakery was provided a CumulusCI mapping file it would use that file to create DB tables. Now it
consistently uses its own table inferencing algorithm. In addition to simplifying the code, this means that record
type columns can be created without adding them to a mapping file.
=> Do not use CCI mapping to create tables.

docs/index.md, snowfakery/template_funcs.py, tests/test_faker.py
=> Check with Faker before dateutil.parser.parse

snowfakery/output_streams.py, tests/test_output_streams.py
=> Parse errors should not cause JSON with close-bracket

requirements.txt, snowfakery/data_generator_runtime.py, snowfakery/output_streams.py
Remove references to annoying date subclass:
https://github.com/joke2k/faker/pull/1258
=> Update to Faker 4.1.3

requirements.txt, requirements_dev.txt
=> Dependency roll-up

examples/salesforce/scripts/test_accounts_npsp.sh, examples/salesforce/scripts/test_contacts.sh, examples/salesforce/scripts/test_contacts_npsp.sh, examples/salesforce/scripts/test_opportunities_npsp.sh
@davisagli asked if we should keep these. I wasn't sure whether to expand them to be more "standalone" (creating their own orgs) or delete them but came down on the side of deleting them.
=> Delete files that don't add much value

snowfakery/cli.py, snowfakery/template_funcs.py, snowfakery/utils/template_utils.py
Opt-in to the new Faker optimizations.
=> Enable Faker optimizations

examples/npsp/Account_npsp.recipe.yml
Comment had a local directory name in it.
=> Remove accidental reference to local directory structure

snowfakery/data_generator_runtime.py, snowfakery/template_funcs.py, tests/test_locale.yml, tests/test_locales.py
Add a feature to Snowfakery to supported scoped locales so that it is easy to make full recipes or regions of recipes which are in a particular locale.
=> Add scoped locale support to Snowfakery

snowfakery/template_funcs.py, tests/test_references.py
Test all error conditions and fix bugs found in the process of testing them. This file now has 100% test coverage.
=> 100% test coverage for template_utils.py plus bug fixes

docs/index.md, examples/test_context.yml, snowfakery/data_generator_runtime.py, snowfakery/data_generator_runtime_object_model.py, snowfakery/parse_recipe_yaml.py, snowfakery/template_funcs.py, tests/test_template_funcs.py
The documentation referred to variables that don't actually exist. So I made some minor naming changes, fixed the docs and added tests to ensure that the documented features don't break.
=> Fix docs about context bugs and add template_filename variable

docs/index.md, tools/docs_samples.py
This tool merges example files into the docs and thus ensures that the tested version of the example is also the one in the doc.
=> Tool for merging example files into docs

docs/index.md, examples/null.yml, snowfakery/template_funcs.py, tests/conftest.py, tests/test_references.py, tests/test_template_funcs.py
YAML uses NULL so now Snowfakery also use NULL in Jinja templates.
=> Add NULL to Snowfakery formulas #239

snowfakery/__init__.py, snowfakery/cli.py, snowfakery/generate_mapping_from_recipe.py, snowfakery/output_streams.py, snowfakery/salesforce.py, tests/cci/record_types.yml, tests/test_generate_mapping.py
I realized that there is a much simpler way to do record types. I guess the first time I implemented it, I didn't really understand CCI's expected format. Now I just fake that format.
CCI will also need a small change to be compatible.
=> Simpler record type handling

snowfakery/data_gen_exceptions.py, snowfakery/data_generator.py, snowfakery/data_generator_runtime.py, snowfakery/generate_mapping_from_recipe.py, snowfakery/output_streams.py, snowfakery/template_funcs.py
DataGenError default to None for the 2nd and 3rd args so it's not necessary to spell them out.
=> DataGenError defaults to None for the 2nd and 3rd

requirements.txt, requirements_dev.txt
Faker is the only updated dependency that is relevant to end-users, and it is a minor change.
=> Dependencies updates.

docs/embedding.md, docs/index.md, examples/sample_app.py, snowfakery/__init__.py, snowfakery/api.py, snowfakery/cli.py, snowfakery/common_entry_point.py, snowfakery/data_generator.py, snowfakery/data_generator_runtime.py, snowfakery/output_streams.py, tests/test_cli.py, tests/test_custom_plugins_and_providers.py, tests/test_data_generator.py, tests/test_data_generator_runtime_dom.py, tests/test_embedding.py, tests/test_references.py
Allow Applications to control some aspects of how Snowfakery works.
Make the Snowfakery CLI into "just another application".
Make a ParentApplication base class that works the same way as the Snowfakery CLI.
Probably easiest to start by reading the docs:
https://github.com/SFDO-Tooling/Snowfakery/blob/dc39e599f5fcaed0b734da50e5f9fd29ecf2c458/docs/embedding.md
=> Parent Application Context

requirements.txt
Add typing-extensions to requirements.txt
=> Add typing-extensions to requirements.txt

docs/index.md, examples/basic-salesforce.recipe.yml, examples/salesforce/person-accounts-plugin.recipe.yml, examples/salesforce/users.yml, snowfakery/data_generator_runtime.py, snowfakery/fakedata/fake_data_generator.py, snowfakery/utils/template_utils.py, tests/test_faker.py
Changes:
1. Faker names are now case-insensitive.
2. Certain "well-known" Salesforce names are available.
3. Emails are now safe ("example.com")
Todo:
* No docs
* Tests should be built up. Especially of failure cases.
=> Faker fixes

snowfakery/data_generator_runtime_object_model.py, snowfakery/fakedata/fake_data_generator.py, snowfakery/utils/template_utils.py, tests/test_faker.py
Force all access to faker through a single method _get_fake_data which allows Snowfakery overrides to be injected into the system.
=> Fix an inconsistency between fake. and fake:

examples/YamlOutputStream.py, plugins/package1/TestOutputStream.py, snowfakery/api.py, snowfakery/cli.py, snowfakery/output_streams.py, snowfakery/plugins.py, tests/test_cli.py, tests/test_images.py, tests/test_output_streams.py
Changes:
1. There was a regression with respect to the Image output formats. This fixes them.
2. Added a unit test to ensure we don't regress.
3. While I was at it, I also added the feature of pluggable output streams.
=> 1. Fix image output. 2. Allow 3rd party outputstreams.

HISTORY.md
=> Small doc update

snowfakery/fakedata/fake_data_generator.py, tests/test_faker.py
Fix regression where function arguments were not passed to faker properly.
=> Pass kwargs to Faker

.github/workflows/ci.yml, pytest_snowfakery/salesforce_cci_pytest_plugin.py, requirements/dev.txt, requirements/prod.in, requirements/prod.txt, snowfakery/standard_plugins/Salesforce.py, tests/test_generate_mapping.py, tests/test_with_cci.py
Make CumulusCI an optional requirement of Snowfakery. If you don't have it installed, some tests will be skipped.
=> Make CumulusCI Optional

.github/workflows/ci.yml, docs/salesforce.md, examples/soql_dataset.recipe.yml, examples/soql_dataset_shuffled.recipe.yml, examples/soql_dataset_shuffled.yml, examples/soql_dataset_where.recipe.yml, pytest_snowfakery/salesforce_cci_pytest_plugin.py, requirements/dev.in, snowfakery/data_generator.py, snowfakery/standard_plugins/Salesforce.py, tests/cassettes/TestSOQLDatasets.test_dataset_bad_query.yaml, tests/cassettes/TestSOQLDatasets.test_soql_dataset_bulk.yaml, tests/cassettes/TestSOQLDatasets.test_soql_dataset_in_order.yaml, tests/cassettes/TestSOQLDatasets.test_soql_dataset_shuffled.yaml, tests/cassettes/TestSOQLDatasets.test_soql_dataset_where.yaml, tests/cassettes/TestSOQLWithCCI.test_find_records_returns_multiple.yaml, tests/cassettes/TestSOQLWithCCI.test_find_records_returns_nothing.yaml, tests/conftest_extras_w_cci.py, tests/test_generate_mapping.py, tests/test_with_cci.py, tools/docs_samples.py
Additional tests and fixes for SOQL in Snowfakery
=> Additional tests and fixes for SOQL in Snowfakery

snowfakery/output_streams.py
https://docs.sqlalchemy.org/en/14/core/metadata.html#sqlalchemy.schema.Table.exists
"Deprecated since version 1.4: The Table.exists() method is deprecated and will be removed in a future release. Please refer to Inspector.has_table()."
=> Clean up SQL Alchemy warning

tests/test_friends.py
Unit test for multiple friends of an object.
=> Test case for multiple friends

docs/salesforce.md, examples/salesforce/UsersProfilesPermissions.yml, tests/cassettes/TestSalesforcePlugin.test_profile_id.yaml, tests/test_salesforce_gen.py
Docs and tests for the Salesforce.ProfileId feature.
=> Docs and tests for ProfileID feature

.github/workflows/ci.yml, .github/workflows/extra-checks-after-pull-request-review.yml, tests/test_with_cci.py, tools/faker_docs_utils/mkdocs_plugins/main_mkdocs_plugin.py
Per #434 
Running docs build so often wastes CPU time and human time. This reduces it somewhat.
=> Run slow docs build only after PR review.

docs/index.md, examples/conditional.yml, examples/random-choice-complex.yml, snowfakery/fakedata/fake_data_generator.py
Add missing documentation for parts of random_docs
=> Better random_choice docs

pytest_snowfakery/salesforce_cci_pytest_plugin.py, tests/cassettes/TestSOQLDatasets.test_soql_dataset_bulk.yaml, tests/conftest_extras_w_cci.py
Update test fixtures to match CCI
=> Update test fixtures to match CCI

snowfakery/data_gen_exceptions.py
This function would sometimes return new exceptions and sometimes return the original. Now it consistently returns a new exception. This makes the exception chaining more reliable.
=> Fix exception handling

snowfakery/data_gen_exceptions.py, snowfakery/data_generator_runtime_object_model.py, snowfakery/template_funcs.py
More exception handling cleanups.
=> Clean up exception handling

snowfakery/standard_plugins/datasets.py
Fix an error reported by a user of an error being reported on Windows. I reproduced it on Windows and then fixed it in this PR.
=> Fix query result closure errors reported on Windows.

docs/index.md, examples/jinja_filters.recipe.yml, examples/price_math.recipe.yml
Add a bit more documentation about Jinja filters.
=> Document Jinja filters better

tools/faker_docs_utils/fakedata_header_full.md
Fix spelling mistake as per #575
=> Fix Aaron's last name

snowfakery/fakedata/fake_data_generator.py, tests/test_custom_plugins_and_providers.py, tests/test_faker.py
Before creating an email address or username from firstname, lastname, check that firstname, lastname are ASCII.
=> Fake data will not generate non-ascii emails or usernames

examples/YamlOutputStream.py, snowfakery/output_streams.py
Work I will do next week will need the OutputStream.close()  method to take another argument so I'm laying the groundwork by making it more flexible.
=> Change the interface for OutputStream.close() to make it more flexible

docs/index.md, snowfakery/docs/examples/st_ives.yml
Fix to match modern code prettying standard.
=> Fix formatting of example YAML

docs/index.md, snowfakery/template_funcs.py, tests/debug.recipe.yml
Usability and doc Improvements to the debug feature.
=> Clean up debug feature

docs/embedding.md, snowfakery/api.py
Very minor type declaration changes.
=> Fix a type declaration

snowfakery/fakedata/fake_data_generator.py
The wrong faker name was overridden and hidden.
=> Fix Date this year feature

.github/workflows/ci.yml, .github/workflows/release.yml
Add workflow_dispatch to a couple of workflows.
=> Allow various workflows to be manually triggered

snowfakery/data_generator_runtime.py, snowfakery/row_history.py
1. Factor out and clarify resave_objects_from_continuation
2. Create all SQL tables and counters up-front instead of lazily
3. isort some imports
=> Three changes.

.github/workflows/ci.yml, requirements/dev.in, requirements/dev.txt, requirements/prod.txt, snowfakery/__init__.py
Add `diff-cover` coverage checking to Snowfakery.
=> Add diff-cover coverage checking to Snowfakery.

examples/bad_soql_dataset.recipe.yml, snowfakery/plugins.py, tests/cassettes/TestSOQLDatasets.test_soql_dataset_error.yaml, tests/test_with_cci.py
Cover some previously uncovered lines.
=> Test enhancements

tools/test_dev_install.sh
This script tests that a Snowfakery dev-install works and also serves as documentation for how to do it.
=> Add test script
